CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  barcode TEXT NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC NOT NULL
);
