// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Product struct {
	ID          int64
	Name        string
	Code        sql.NullString
	Barcode     sql.NullString
	Description sql.NullString
	Price       float64
}
