// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"
	"database/sql"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (name, code, barcode, description, price) 
VALUES (?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	Name        string
	Code        sql.NullString
	Barcode     sql.NullString
	Description sql.NullString
	Price       float64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.Name,
		arg.Code,
		arg.Barcode,
		arg.Description,
		arg.Price,
	)
	return err
}
