// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package store

import (
	"context"
)

const createAddress = `-- name: CreateAddress :exec
INSERT INTO addresses (city, state, country, postal_code, street, stree_number, phone_number, tax_id, email) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAddressParams struct {
	City        string
	State       string
	Country     string
	PostalCode  string
	Street      string
	StreeNumber string
	PhoneNumber string
	TaxID       string
	Email       string
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) error {
	_, err := q.db.ExecContext(ctx, createAddress,
		arg.City,
		arg.State,
		arg.Country,
		arg.PostalCode,
		arg.Street,
		arg.StreeNumber,
		arg.PhoneNumber,
		arg.TaxID,
		arg.Email,
	)
	return err
}

const getAddressess = `-- name: GetAddressess :many
SELECT id, city, state, country, postal_code, street, stree_number, phone_number, tax_id, email FROM addresses
`

func (q *Queries) GetAddressess(ctx context.Context) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getAddressess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.State,
			&i.Country,
			&i.PostalCode,
			&i.Street,
			&i.StreeNumber,
			&i.PhoneNumber,
			&i.TaxID,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
