// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package store

import (
	"context"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO clients (name) 
VALUES (?)
`

func (q *Queries) CreateClient(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createClient, name)
	return err
}

const getClients = `-- name: GetClients :many
SELECT id, name FROM clients
`

func (q *Queries) GetClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
