// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folios.sql

package store

import (
	"context"
)

const createFolio = `-- name: CreateFolio :exec
INSERT INTO folios (type, count) 
VALUES (?, 1)
`

func (q *Queries) CreateFolio(ctx context.Context, type_ string) error {
	_, err := q.db.ExecContext(ctx, createFolio, type_)
	return err
}

const getFolios = `-- name: GetFolios :many
SELECT id, type, count FROM folios
`

func (q *Queries) GetFolios(ctx context.Context) ([]Folio, error) {
	rows, err := q.db.QueryContext(ctx, getFolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folio
	for rows.Next() {
		var i Folio
		if err := rows.Scan(&i.ID, &i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCount = `-- name: IncrementCount :exec
UPDATE folios
SET count = count + 1
WHERE id = ?
`

func (q *Queries) IncrementCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementCount, id)
	return err
}
