// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Product struct {
	ID          int64
	Name        string
	Code        string
	Barcode     string
	Description string
	Price       float64
}
