// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_items.sql

package store

import (
	"context"
)

const addTransactionItem = `-- name: AddTransactionItem :exec
INSERT INTO transaction_items (quantity, product_id, transaction_id) 
VALUES (?, ?, ?)
`

type AddTransactionItemParams struct {
	Quantity      float64
	ProductID     int64
	TransactionID int64
}

func (q *Queries) AddTransactionItem(ctx context.Context, arg AddTransactionItemParams) error {
	_, err := q.db.ExecContext(ctx, addTransactionItem, arg.Quantity, arg.ProductID, arg.TransactionID)
	return err
}
