// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package store

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (date, client_id, address_id, folio, folio_type) 
VALUES (?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	Date      time.Time
	ClientID  int64
	AddressID int64
	Folio     int64
	FolioType int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.Date,
		arg.ClientID,
		arg.AddressID,
		arg.Folio,
		arg.FolioType,
	)
	return err
}

const getTransactionInfo = `-- name: GetTransactionInfo :one
SELECT t.id, date, folio, client_id, address_id, folio_type, c.id, name, a.id, city, state, country, postal_code, street, stree_number, phone_number, tax_id, email, f.id, type, count FROM transactions t
JOIN clients c ON t.client_id = c.id
JOIN addresses a ON t.address_id = a.id
JOIN folios f ON t.folio_type = folios.type
WHERE t.id = ?
`

type GetTransactionInfoRow struct {
	ID          int64
	Date        time.Time
	Folio       int64
	ClientID    int64
	AddressID   int64
	FolioType   int64
	ID_2        int64
	Name        string
	ID_3        int64
	City        string
	State       string
	Country     string
	PostalCode  string
	Street      string
	StreeNumber string
	PhoneNumber string
	TaxID       string
	Email       string
	ID_4        int64
	Type        string
	Count       int64
}

func (q *Queries) GetTransactionInfo(ctx context.Context, id int64) (GetTransactionInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionInfo, id)
	var i GetTransactionInfoRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Folio,
		&i.ClientID,
		&i.AddressID,
		&i.FolioType,
		&i.ID_2,
		&i.Name,
		&i.ID_3,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.Street,
		&i.StreeNumber,
		&i.PhoneNumber,
		&i.TaxID,
		&i.Email,
		&i.ID_4,
		&i.Type,
		&i.Count,
	)
	return i, err
}

const getTransactionItems = `-- name: GetTransactionItems :many
SELECT t.id, date, folio, client_id, address_id, folio_type, quantity, product_id, transaction_id, p.id, name, code, barcode, description, price FROM transactions t
JOIN transaction_items ti ON t.id = ti.transactions_id
JOIN products p ON ti.product_id = p.id
WHERE t.id = ?
`

type GetTransactionItemsRow struct {
	ID            int64
	Date          time.Time
	Folio         int64
	ClientID      int64
	AddressID     int64
	FolioType     int64
	Quantity      float64
	ProductID     int64
	TransactionID int64
	ID_2          int64
	Name          string
	Code          string
	Barcode       string
	Description   string
	Price         float64
}

func (q *Queries) GetTransactionItems(ctx context.Context, id int64) ([]GetTransactionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionItems, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionItemsRow
	for rows.Next() {
		var i GetTransactionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Folio,
			&i.ClientID,
			&i.AddressID,
			&i.FolioType,
			&i.Quantity,
			&i.ProductID,
			&i.TransactionID,
			&i.ID_2,
			&i.Name,
			&i.Code,
			&i.Barcode,
			&i.Description,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, date, folio, client_id, address_id, folio_type FROM transactions
`

func (q *Queries) GetTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Folio,
			&i.ClientID,
			&i.AddressID,
			&i.FolioType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
