// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Create(arg1:store.CreateAddressParams):Promise<void>;

export function GetAll():Promise<Array<store.Address>>;
