// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['tasks']['Folio']['Create'](arg1);
}

export function GetAll() {
  return window['go']['tasks']['Folio']['GetAll']();
}

export function Increment(arg1) {
  return window['go']['tasks']['Folio']['Increment'](arg1);
}
