// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['tasks']['Product']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['tasks']['Product']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['tasks']['Product']['GetAll']();
}

export function Update(arg1, arg2) {
  return window['go']['tasks']['Product']['Update'](arg1, arg2);
}
