// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Create(arg1:store.CreateProductParams):Promise<void>;

export function Delete(arg1:number):Promise<void>;

export function GetAll():Promise<Array<store.Product>>;

export function Update(arg1:store.CreateProductParams,arg2:number):Promise<void>;
