// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {tasks} from '../models';

export function AddItem(arg1:store.AddTransactionItemParams):Promise<void>;

export function Create(arg1:store.CreateTransactionParams):Promise<void>;

export function Get(arg1:number):Promise<tasks.FullTransaction>;

export function GetAll():Promise<Array<store.Transaction>>;
