// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1) {
  return window['go']['tasks']['Transaction']['AddItem'](arg1);
}

export function Create(arg1) {
  return window['go']['tasks']['Transaction']['Create'](arg1);
}

export function Get(arg1) {
  return window['go']['tasks']['Transaction']['Get'](arg1);
}

export function GetAll() {
  return window['go']['tasks']['Transaction']['GetAll']();
}
