// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ShowConfirm(arg1:string,arg2:string):Promise<boolean>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;
