// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function DeleteProduct(arg1:number):Promise<void>;

export function GetAllProducts():Promise<Array<store.Product>>;

export function Greet(arg1:string):Promise<string>;

export function ShowConfirm(arg1:string,arg2:string):Promise<boolean>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function UpdateProduct(arg1:store.UpdateProductParams):Promise<void>;
